### ISSUE TITLE
TE-112: Known Bugs - EPIC

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#112]
- [x] 1. Roles module: In edit role screen the buttons of "select all" have to be "unselect all" too
- [x] 2. Users module: When editing user, I need to select I agree to license agreement! again - this should be removed completely from editing form
- [x] 3. Users module: Some countries don't have cities like Niue and Norfolk Island - either remove those countries or make the city not required in that case

**Comment by babanesma** [comment]
@badr4php , if there is already selected privilege and I press select all button , the first action should be to select all privileges not to deselect
