### ISSUE TITLE
QA Issues EPIC

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#135]
### Testing Centers
- [x] when saving the testing center, if some of the days disabled and working hours removed, this is not being saved. 
- [x] secondary phone shouldn't be mandatory

### Testing Providers
- [x] on create/edit if selecting non existing (TPM) users it leads to error page  

### Test Appointment 
- [x] test appointment is mandatory condition while test taker trying to do exam, give it allowance of 30 minutes maximum after which the test taker cannot do his/her exam.
- [x] when test is scheduled with one test center, all other test centers where test is available disappears, they should be displayed without being able to schedule the test with them
- [x] when click cancel appointment, a message appear asking to confirm, if the user clicks on "cancel" in the confirmation box, a paypal button appears in the page
- [x] user needs create appointment button
- [x] in admin listing - error

### Questions
- [x] in frontend of hot text question type, make indentation to text.
- [x] when saving questions it's return fatel error because the validation array not return it's return null
- [x] the multimediathe of select point question must be requried model answers of select point question type not saved because the body attribute should be not required
- [x] when create the slider question type when save the correct value take the value of min value
and when editing the value not populate
- [x] the places of min and max values of slider question type should be fixed in front end like it exist in the desktop
- [x] we should remove the including of maphilight.min.js file from hotspot question view in front end
because it not exits  and not used
- [x] create model answers in seed file for graphic association, association  and matching questions to be each two models related to each other . in hotspot question make only one be right answer and the other not.
- [x] fix the style of lines of related divs for question was answer before in graphic association question in frontend
- [x] in ordering question type when back to question i answerd before and want to change my answer the answer object i build from begining not containue on my old answer
- [x] in ordering question type when back to question i submit it without answer after two time it make error.
- [x] in Slider question type we should make validation of values of min, max and correct to be integer
- [x] we should populate the editing of Slider question type
- [x] we should change the place of coordinates message error in graphic gap question in backend
when we saved without choice the coordenates
- [x] in graphic association question when we don't select the related coordinates the model answer not saved without display error so we should display error when this is happen.
- [x] change the color of related coordinates from white to another color in graphic association question
- [x] change the validator of moderl answer in select point question from (This question should only has three model answers with one right answer) to be ( This question should only has one model answer with right answer !)
- [x] adding multimedia while creating extended answer questions leads to error page
- [x] creating model answers for drag/drop questions leads to error page

### Correction
- [x] we should be fix the correction method for association and matching questions.
- [x] in Drag and Drop Question we should set the status of question  when the question is incorrect
- [x] in Hot Text Question we should set the status of question  when the question is incorrect
- [x] in Multiple choice Question we should set the status of question  when the question is incorrect
- [x] in General method for correction we should set the status of question  when the question is incorrect

### Settings
- [x] Remove create question type
- [x] Remove delete question type
- [x] Hide add new email button in settings page
- [x] Remove create new email button in emails page                        
- [x] No emails sent for any actions                        
- [x] We couldn't create certificates                                           
- [x] Blueprint total should be 100% not more not less
- [x] Emails - delete action shouldn't be allowed

### Tests
- [x] Topics total must be equal 100%
- [x] Exam results report - unanswered questions should be displayed
- [x] Certificate field shouldn't be mandatory

 

### Categories
- [x] Category name must be unique

### Users
- [x] Import users should be bulk user registration with no test appointments (hide date, test center, test provider, test)
- [x] While editing user profile the secondary phone field shouldn't be mandatory
- [x] When created/modify user profile user has to change the country in order to get list of cities

### Exams
- [ ] Time counter is showing NAN
- [x] Available questions are 9 only 3 shows up for the users

### Vouchers
- [x] Change the label of "Vouchers Number" to "Number of Vouchers"

### General
- [x] Change the icons of activate/deactivate/delete to ones attached in file
- [x] Stop/hide all delete actions
- [x] in case of deactivation of entities in (emails, categories) the icons are not organized
- [x] on printing report the buttons should be hidden

### Reports
- [x] Fix report 2
- [x] Fix report 21
- [x] Fix report 22

**Comment by badr4php** [comment]
I am working on Questions part.
