### ISSUE TITLE
QA Issues EPIC #137

### ISSUE THREAD

**Issue by AbdElmoneimMohamed** [camelcasetechsd/testing-engine#137]
### Exam
- [x] User can start exam from url without validation in frontend and desktop.
- [x] Restrict the exam to questions that have model answers ( one exception allowed which is the extended answer questions )

### General 
- [x] http://git.camelcasetech.com/camelCase/testing-engine/pulls/30#issuecomment-42
- [x] Implement the new icons of Activate/Deactivate/Delete
- [x] Search for emails
### Certificates
- [x] Make the same switch case of image types when creating the certificates as we did in uploading certificates 
- [x] Make sure there's no error in frontend in case the exam doesn't have associated certificate
- [x] Add `End Exam Correction` to exams that have `Extended Answers` questions, to create the certificate after finishing all the corrections. 

### Logs 
- [x] Log files are empty 

### Payments
- [x] Save the user transaction of the payment data in testing engine database along with its state

### Test Appointment 
- [x] The user cannot do test appointment reschedule
- [x] The user cannot cancel the test appointment
