### ISSUE TITLE
QA Issues EPIC #138 bug

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#138]
### Test Appointment
- [x] Reschedule exam will be made through “PayPal” only, even if reschedule charge is “0” - **p1**
- [x] “PayPal” should be opened in new tab, not at the same tab. - **p2**

### Exam Results
- [x] When access exam result for the “emp2@domain.com” user, I got the following error code - **p1** - **cannot replicate**
- [x] Exam report before finish the exam has incorrect answers in Q03 This question type is “Association” - **p2**

### Exam
- [x] There are some questions need to be adjusted. They are opened in exam with their answers. **p1**
- [x] When exam is finished for some user, the same user cannot take the same exam again. - **p2**

### Error Handling
- [x] We need error handling page - **p2**
