### ISSUE TITLE
TE-148 : Issues To Re-Check

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/testing-engine#148]
- [x] Issue 37 : Exam Result	The result appears in the below report is not logic. ( #154 )
- [x] Issue 41 : Exam delivery	There are some questions need to be adjusted. They are opened in exam with their answers. ( #156 )
- [x] Issue 42 : Exam delivery	Some questions need to be adjusted with its model answers. They are evaluated as wrong while they are correct. ( #157 )
- [x] Issue 43 : Exam delivery	"When exam is finished for some user, the same user cannot take the same exam again.
Test taker must be able to reschedule the same exam after the exam is submitted."
- [x] Issue 44 : Exam result	"http://testing-engine.camelcasetech.com/exams/591015a0da7a5/summary
Exam report before finish the exam has incorrect answers in Q03
This question type is “Association”"
- [x] Issue 46 : Schedule Appointment	"http://testing-engine.camelcasetech.com/tests/2
When click on schedule, appointment is scheduled, but system logout." ( #164 )
- [x] Issue 48 : Exam answer sheet.	Exam answer sheet must take the last answer only for each question; whatever the number of trying solving that question. ( #158 )
- [x] Issue 52 : Question export	Question export is not working. (#165)
- [x] Issue 54 : Exam Questions	The below selected question is changed as type and model answers after the test taker finish the exam. During the exam, its type was extended answer. 
Result sheet is not keeping the exam as it is.
http://thetalenttier.net/admin/tests/exams/16/answers?page=1 
**Tech Note :**  Remove the question type from edit page
