### ISSUE TITLE
TE-185 : Update Deactivated Model Answers

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/testing-engine#185]
- [x]  when saving the updates of deactivate model answer of select point question we get this error #130 

- [x]  when saving the updates of deactivate model answer of hot text question we get  error #127 

- [x]  when saving the updates of deactivate model answer of ordering question we get  error  #120 

- [x] when saving the updates of deactivate model answers in slider question we get error

- [x] when saving the updates of deactivated model answers in graphic association question we get error

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/camelCase/testing-engine/pulls/100
