### ISSUE TITLE
TE-24: Tests CRUD

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#24]
Points: 20
Estimated Time: 11 days
Actual Time: -
(Sprint 3)
- Test fields: name, description, code, provider, duration, tag, category, schedule fees, reschedule fees, cancellation fees, type ( exam, practice ), formation ( blueprint, weight ), topics ( with default topic )
- Category fields: name, description
---------------------------------------------------------------------------------------
(Sprint 4)
- Questions field: 
    - type ( multiple choice single, multiple choice multiple, true/false, drag/drop, short answer, extended answer)
    - Multimedia ( upload or embedded video )
    - Body
    - Answers
        - single choice: multiple fields with radios ( add more button - max according to settings )
        - multi choices: multiple fields with checkboxes  ( add more button  - max according to settings)
        - true/false: radio buttons
        - drag/drop: (((suspended)))
        - short answer: placeholder in the body of the question, and textfield for the answer
        - extended answer: NA
    - topic ( default selected )
    - weight
- Questions list: as tab inside the details page of test

## Subtasks 
- [x] Create Test Entity and Related Entities #33
- [x] Categories Listing #34
- [x] Categories form for creating and updating #35
- [x] Categories Unit Testing #36
- [x] Tests Listing #37
- [x] Tests form for creating and updating #38 
- [x] Tests unit testing #39
- [x] Topic Entity #40
- [x] Topic impact on Test form #41
- [x] Topics unit testing #42
- [x] Question Type Entity #43
- [x] Question and Model Answer entities #44
- [x] Questions and Model Answers impact on Test form #45
- [x] Questions list tab in details page of test #46 
- [x] Questions and Model Answers unit testing #47
