### ISSUE TITLE
TE-3: Building Registration

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#3]
Points: 8
Estimated Time: 3 days
Actual Time: -

## SubTasks
- [x]  Wirefame Preparation
- [x]  Building Registration Form 
- [x]  Registration Form Validation
- [x] Store to Database
- [x] Email Notification
- [x] User Activation
- [x]  Building Profile Form
- [x]  Profile Form Validation

---

**User Fields:**
- **Required:**
  - ID
  - First Name (Given)
  - Last Name (Surname)
  - Address Line 1
  - City
  - Country
  - State/Province
  - Zip/Postal Code
  - Primary Phone
  - E-Mail Address
  - Confirm E-Mail Address
  - Password
  - Confirm Password
  - Reminder Question
  - Reminder Answer
  - Confirm Answer
  - Do you agree with the Privacy Notice?
  - DOB
  - POB
- **Optional:**
  - Middle Initial
  - Language
  - Address Line 2
  - Company Name
  - First Name (in non-English character language)
  - Last Name (in non-English character language)
  - Address Line 1 (in non-English character language)
  - Address Line 2 (in non-English character language)
  - Address Line 3 (in non-English character language)
  - City (in non-English character language)
  - State/Province (in non-English character language)
  - Country (in non-English character language)
  - Postal Code (in non-English character language)
  - Secondary Phone
  - Fax Number

**Comment by ahmedelbougha** [comment]
Attaching initial wireframes ( not approved yet )

![registration](https://cloud.githubusercontent.com/assets/8982139/19763386/16746f16-9c3e-11e6-8d08-45737b982699.png)

![profile](https://cloud.githubusercontent.com/assets/8982139/19763385/164b7c50-9c3e-11e6-89f4-324372385332.png)

**Comment by ahmedelbougha** [comment]
Wireframes have been sent to the client, waiting for their response.

**Comment by ahmedelbougha** [comment]
By end of first sprint, this still pending on client response to wireframes.

**Comment by babanesma** [comment]
### Profile module 
- [ ] group all the routes to have under `Route::group(['middelware' => 'auth'])` , see example here https://laravel.com/docs/5.3/routing#route-group-middleware
- [ ] remove `{id}` from the routes , get the user from the Auth facade and make corresponding changes in Profile Controller
- [ ] don't use admin models nor requests classes in front end modules and vice versa , because we might implement other solutions in front end different than admin , create new models and requests

### Registration
- [ ] Also don't use admin models nor requests , create new ones for auth controllers 

### General 
- [ ] Correct the front end layout `resources/themes/frontend_default/layouts/app.blade.php` to load front end css and js rather than admin's

**Comment by ahmedelbougha** [comment]
QA issues:
- [ ] Password/Confirm Password fields have to be not less than 6 characters long
- [ ] When clicking on _I agree to license agreement!_ it doesn't show the agreement modal
- [ ] The user is redirected to Login screen after registration with no flash message
- [ ] The user can login directly after registration without confirming the link by email
- [ ] The confirmation email queue seems to be not working

**Comment by babanesma** [comment]
@AbdElmoneimMohamed , output a confirmation message when the user clicks on the activation link in the email saying that his account is activated and he can login
