### ISSUE TITLE
TE-4: Roles and Permissions ( ACL )

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#4]
Points: 8
Estimated Time: 3 days
Actual Time: -

each user has one or more roles
∘ each role has one or more permissions
∘ according to permissions, the user can access particular features, functions, pages
∘ roles and permissions and their relation to user save in DB ? yes
∘ using Laravel ready made authorization package? yes
∘ save in user session? yes
∘ impact on users module? to add roles multiselect or checkbox group
∘ adding all roles according to ( 4.4. User Roles ) in addition to superadmin role
∘ unit and behavior test? yes
∘ crud for roles
∘ crud for permissions

## Subtasks
- [x] Roles Entity #7 
- [x] Roles User Relationship #8
- [x] Role Crud #9 
- [x] Privileges Form #10 
- [x] Implementing Roles Impact on User Form #11 
- [x] Implementing Session #12 
- [x] Unit Testing and Behavior Testing #21

**Comment by ahmedelbougha** [comment]
QA Issues:

- [ ] Upon disabling a role, the icon of _view_ is displayed over _reactivate_ icon

**Comment by ahmedelbougha** [comment]
QA Issues:

[ ] Super Admin role must be avoided to delete/disable

**Comment by ahmedelbougha** [comment]
Issues:
- [ ] The buttons of "select all" has to "unselect all" too

**Comment by ahmedelbougha** [comment]
moving this to _**Done**_ with one know issue in (1) in EPIC #112
