### ISSUE TITLE
TE-49: Logs

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#49]
Points: 5
Estimated Time: 3 days
Actual Time: -
(Sprint 6)

Taking Drupal logs as reference:

- Listing Page: Showing the following data of the log (**Check the attached screenshot for more details**)
    
     - Type: ( PHP, System, User, Access Denied ) also shows the Severity (as icon)
     - Date
     - Message: Trimmed version of the message
     - User
     - **Operations: _This can be ignored_**
     - Also, you can filter the logs by Type and Severity

- Details Page: Showing the details of an error  (**Check the attached screenshot for more details**) including:
    - Date
    - User
    - Location in the system (URL)
    - Referrer 
    - Message: Full message
    - Severity
    - Hostname
    - **Operations: _This can be ignored_**

![drupal-logs](https://cloud.githubusercontent.com/assets/8982139/20967191/cc21b2c0-bc86-11e6-92a9-1854591720ac.png)

![drupal-logs-details](https://cloud.githubusercontent.com/assets/8982139/20967330/93a9e56a-bc87-11e6-997e-b5cf174bd1f9.png)

## SubTasks

- [x] install [laravel log viewer plugin](https://github.com/rap2hpoutre/laravel-log-viewer)
- [x] create new service provider to save log entries in storage/logs/application.log #50
- [x] create new module in admin and new controller to view logs #51
- [x] Logs Module unit testing #62
