### ISSUE TITLE
TE-5: Testing Centers CRUD

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#5]
Points: 8
Estimated Time: 6.5 days
Actual Time: -

∘ saving in db
∘ listing, filter, sort, pagination
∘ in details the TCAs users are linked to their profiles
∘ user to be assigned TCA role before can be assigned to test center
∘ notifications
∘ unit and behavior tests
∘ add ip address, working days, working hours to wireframes

## Subtaks
- [x] Issue #16 : Create Testing Center entity
- [x] Issue #17 : Create Testing Center listing
- [x] Issue #18 : Testing Center form for creating and updating
- [x] Issue #19 : Testing Center unit testing and behavior testing
- [x] Issue #20 : Adjust user model after testing center changes

**Comment by ahmedelbougha** [comment]
Wireframes:

![edit](https://cloud.githubusercontent.com/assets/8982139/20036236/3c5c47e2-a40b-11e6-8ac7-1f04c21a7df1.png)
![create](https://cloud.githubusercontent.com/assets/8982139/20036237/3c82a0c2-a40b-11e6-83c7-17e0c61c1481.png)
![details](https://cloud.githubusercontent.com/assets/8982139/20036238/3c9129c6-a40b-11e6-87cc-9a8bd01ad54e.png)
![list](https://cloud.githubusercontent.com/assets/8982139/20036239/3c957828-a40b-11e6-923b-de7047963a9f.png)

**Comment by ahmedelbougha** [comment]
QA Issues:

- [ ] Trying to edit a _deactivate_ testing center leads to exception page
- [ ] Selecting testing center admin users is supposed to be auto complete field

**Comment by ahmedelbougha** [comment]
All the issues above were not resolved!
![testing engine camelcasetech com-edit-deactivated-center](https://cloud.githubusercontent.com/assets/8982139/21191333/78d8ebcc-c22d-11e6-950a-1cee05aa8987.png)

**Comment by babanesma** [comment]
- [ ] remove function `autocomplete` from ModelAbstract
- [ ] move function `getUsersWithRole` to Admin Users Model 
- [ ] remove the functionality of setting the testing centers by ajax ( function setAdmin in TestingCentersController ) , and retrieve the id and name from the list populated by autocomplete/typeahead function 
To load objects instead of simple string check this link https://github.com/bassjobsen/Bootstrap-3-Typeahead#using-json-objects-instead-of-simple-strings 
- [ ] Make js validation on adding the same user as TCA or exclude the already added TCAs from the query that retrieves the TCA that are showing in the autocomplete list

**Comment by ahmedelbougha** [comment]
Blocked until we finalize the new interface of selecting admins.
