### ISSUE TITLE
TE-53: Tests - Frontend

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#53]
Points: 20
Estimated Time: 14 days
Actual Time: -
(Sprint 6 and Sprint 7)

- Tests Listing Page
    - Shows map of testing centers
    - Table fields:
        - Category
        - Code
        - Test Name
        - Test Type
        - Test Provider
        - more link
- Search for Tests
    - Search by:
        - Name
        - Code
        - Type
        - Provider
- Schedule/Reschedule/Cancel Test Appointment

## SubTasks
- [x] Changes in Tests and Test Centers Admin #63
- [x] Create Test Listing in Frontend #64
- [x] Tests Search  #65
- [x] Test Details Page #68
- [x] Test Appointment #66
- [x] Tests Frontend unit testing #67
