### ISSUE TITLE
TE-54: Admin Backend Reports

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#54]
#### Example Reports
[Certiport Reports Contents.xlsx](https://github.com/camelcasetechsd/testing-engine/files/910579/Certiport.Reports.Contents.xlsx)

### Description 
> The Test Engine will be developed to allow customization and generation of all relevant reports on the multiple system's features.
> The TEM will be able to customize reports and save them to run them later.
> To create a custom report , the TEM will have to choose a base entity/entities on which he will create the report , then choose the parameters he needs to show in the report , for each parameter he should choose the constraints . Then there will be an option to save the report's query to run it later .

### Main Entities ( the admin user will report them )
1. User 
2. Test
3. Exam 
4. TestAppointment
5. Log

### SubTasks
- [x] Create new submodule in admin ( /admin/backend/reports ) with all its configuration ( `config/menu` , `config/modules.php` ) and routes 
- [x] Create new entity that will hold the saved reports 
- [x] Create form for create/update saved reports
- [x] Create page to run the reports and 
- [x] Unit Testing

**Comment by ahmedelbougha** [comment]
Comments of the client:

1. Add the ability to select from multiple related tables
2. Add the ability of grouping
3. Add the ability of sorting (per field)

**Comment by babanesma** [comment]
pull request : https://git.camelcasetech.com/camelCase/testing-engine/pulls/20
