### ISSUE TITLE
TE-55: Admin Settings

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#55]
### Description 
> - Question Types CRUD ( soft deleting ) 
> - Website Emails CRUD 

### SubTasks
- [x] create new module ( `/admin/settings` ) with all its configuration 
- [x] create question types CRUD ( entity already created before )
- [x] create website emails CRUD 
  - Create default record of communication email ( and make it used by default in all emails )
  - create form for create/update website emails

**Comment by babanesma** [comment]
@badr4php 
- Question Types Crud is good 
- in the settings 
  - remove default and email columns
  - add key , value columns that will hold the data for emails 
  - add new seed in `database\seeds` and refer to it in `database\seeds\Databaseseeder.php` to add only one row in settings table with ( key=`From_Email` & value = `no_reply@testing-engine.com` )
  - make sure that the activation email `App\Admin\Users\Http\Mail\User` is using this email 
  - put the `From_Email` key in new constant in Setting Entity class to use it everywhere else
