### ISSUE TITLE
TE-56: Test Appointments Frontend

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#56]
## SubTasks

- [x] Create admin backend for test appointments and exams ( listing only and show details ) #70 
- [x] exam engine ( require authentication of user ) 
  - [x] main exam process
  - [x] exam timer 
  - [x] exam shuffling system #71 
  - [x] exam grading and certification system #72

**Comment by babanesma** [comment]
@AbdElmoneimMohamed 
timer is not resetting when the exam finished and the browser is not closed
