### ISSUE TITLE
TE-58: Test Center and Workstations Frontend

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#58]
### Description 
> - TCA access
>   - Changing Workstation Assigned
>   - Listing Tests Assigned
>   - Change Test Center information
>   - Workstations CRUD ( Create, Read, Update & Delete)

### Technical Notes
All of these pages or access that are required for the TCA role are already implemented in the admin modules but their access is only given to the super admin role 

### SubTasks
- [x] modify `/database/seeds/RolePrivilegesSeeder.php` to add privileges to TCA role for the following 
  - Testing Centers ( only lists the testing centers he is assigned to ) along with its labs and workstations
  - Tests ( only lists the tests assigned to the testing centers he is assigned to ) along with its questions 
- [x] the above modifications will require some changes to the Request classes used in these controllers
- [x] specific unit testing for this role

**Comment by babanesma** [comment]
These commits belongs here 

https://github.com/camelcasetechsd/testing-engine/commit/53dbe4746841ab379b725994a5844c26c2913ea5
https://github.com/camelcasetechsd/testing-engine/commit/25ddbabd6e039e3f6ed19d6f1a9f1b11f8af8997
https://github.com/camelcasetechsd/testing-engine/commit/69daba49d5bcfa2e18ac33489a334ae39c0829f0
