### ISSUE TITLE
TE-59: Localization

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#59]
> - The website can be served in 2 languages : English and Arabic. Can add more languages in the future.
> - Each language has different style based on the orientation ( left-to-right or right-to-left ).
> - When switching from language to another , the content should be translated to the destination language. This content will include :
>   - Static pages
>   - Menus and headers
>   - Forms Labels

## SubTasks
- [ ] Preparing Language files for English and Arabic
- [ ] Add new plugin viewed in the header of frontend and admin pages by which we can set the locale 
- [ ] Translating all static text in all templates 
- [ ] Translating menus ( `config\menus.php` )
- [ ] Translating Forms Labels
