### ISSUE TITLE
TE-60: Payment

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#60]
#### 1. Tests Module Changes
> - Add / Update exam vouchers.
>   - There will be an option for each exam to be sold only by voucher not by visa/paypal like the usual way
>   - The TEM ( Test Engine Manager ) can create these vouchers and assign them to each exam
>   - The Test Provider can request these vouchers through a request form for the exam that he has created and then the TEM can approve them.

#### 2. Payment Module
> 1. Users will securely pay on the website for the following services
>   1.1. Schedule any test according to the prices set before by TPM.
>   1.2. Reschedule the test.
>   1.3. Cancel the test ( either pay for cancellation fees ~or subtract from returned fees~ )
> 2. Payment will be done through the following methods
>   2.1. PayPal
>   2.2. Visa/Mastercard
>   2.3. Voucher

#### 3.TPM voucher form 
> The TPM can request voucher ( eligibility codes ) for each exam and this should be approved by admin ( TEM ).

### Technical Notes
- We will use [Omnipay](http://omnipay.thephpleague.com/) to handle payment gateways 
- We will use this laravel plugin ( https://github.com/ignited/laravel-omnipay )  to integrate omnipay with laravel 

### SubTasks
- [x] Add the payment step before doing any action regarding the scheduling of the tests . Successful payment leads to successful action while failed payment should cancel the whole operation
- [x] Payment using voucher
- [x] Add request form accessed by the TPM to request vouchers for the tests he has added

**Comment by AbdElmoneimMohamed** [comment]
We will use https://github.com/thephpleague/omnipay-migs to implement the CreditCard payment method
But to use this package we must have [MerchantId, MerchantAccessCode, SecureHash], But this parameter We should be able to obtain this directly from the merchant bank
