### ISSUE TITLE
TE-61: Desktop Application

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#61]
### Description 

> This application should be distributed by the Testing Engine to the Testing Centers.
> The Test Taker can log in using his credentials to view the available tests that he has scheduled using the web portal .
> Before the Test Taker can start his exam , one of the TCPs available in the Testing Center should approve all the details of the appointment.

> During the exam, the desktop application should lock all other applications on this workstation, so the test taker can only open the exam and nothing else. After the end of the exam, the application should send the exam results should be sent back to the web portal database. The application should print out the results also send these results to the applicant’s email.

> Note: ​ If the internet goes down at the test center while the exam is being running , the desktop application should continue running until the exam ends. The exam results should be saved locally and then sent back to the server when the internet goes up again.

### Sub Tasks
- [x] Choose the desktop app technology stack #76 
- [x] build API to interact with the desktop app #77
- [x] Build the login 
- [x] Build the exam process 
- [x] Fix how the express app work on the dev server #84
- [x] Implement missing features in desktop app  #85
